### ISSUE TITLE
Mouse Region and Move Cursor bindings 

### ISSUE THREAD

**Issue by PSebs** [Supreeeme/extest#1]
It seems like these are the only two things that doesn't fare well with this as the cursors are still invisible. The rest of the mouse related bindings and input styles seem to work. Tested in both the desktop and Cookie Clicker

**Comment by Supreeeme** [comment]
Should be fixed now, can you confirm?

**Comment by PSebs** [comment]
Both seems to work fine in-game and desktop now.
