### ISSUE TITLE
how do i compile as 64bit?

### ISSUE THREAD

**Issue by MariahWest01** [Supreeeme/extest#16]
im trying to follow [this](https://swg-empire.de/post/842090) and it says to compile extest as 64bit but idk how

**Comment by Supreeeme** [comment]
You can build 64 bit like so:
```
cargo build --target=x86_64-unknown-linux-gnu --release
```

**Comment by MariahWest01** [comment]
do i need steam for this to work? onboard isnt typing

**Comment by Supreeeme** [comment]
Did you use `LD_PRELOAD` as shown in the readme? The 64bit build will be in `target/release/libextest.so`

**Comment by MariahWest01** [comment]
yes i run `env LD_PRELOAD=/usr/lib64/libextest.so onboard`

**Comment by Supreeeme** [comment]
Is libextest.so actually in `/usr/lib64`? It won't be installed there by default.

**Comment by MariahWest01** [comment]
i copied it there

**Comment by MariahWest01** [comment]
i get `env LD_PRELOAD=/home/mariah/Downloads/extest/target/x86_64-unknown-linux-gnu/release/libextest.d onboard
ERROR: ld.so: object '/home/mariah/Downloads/extest/target/x86_64-unknown-linux-gnu/release/libextest.d' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/home/mariah/Downloads/extest/target/x86_64-unknown-linux-gnu/release/libextest.d' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/home/mariah/Downloads/extest/target/x86_64-unknown-linux-gnu/release/libextest.d' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/home/mariah/Downloads/extest/target/x86_64-unknown-linux-gnu/release/libextest.d' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
15:25:12.289 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.` running `env LD_PRELOAD=/home/mariah/Downloads/extest/target/x86_64-unknown-linux-gnu/release/libextest.d onboard`. right now im in gnome as i need a touch keyboard

**Comment by Supreeeme** [comment]
You should be preloading libextest.so, not libextest.d

**Comment by MariahWest01** [comment]
oh ok

**Comment by MariahWest01** [comment]
should i move the library somewhere else

**Comment by MariahWest01** [comment]
![Screenshot_20240715_211419](https://github.com/user-attachments/assets/f3e71715-e612-44bc-a040-5f047f8b8875)
i get this on kde. screenshot because i cant type
