### ISSUE TITLE
extest causing lag in Steam Big Picture Mode when switching in from desktop

### ISSUE THREAD

**Issue by Zeglius** [Supreeeme/extest#17]
Seems preloading extest is causing severe lag as per title described. The lag doesnt happen when steam is launched directly with `steam -tenfoot`, only when switching into BPM from the Steam client.

More context can be found here https://github.com/ublue-os/bazzite/issues/1675

**Comment by Supreeeme** [comment]
Interesting, that's very strange.
I plan to look into this, but I'd also like to point out in the mean time if you're using KDE Plasma 6.1+ you shouldn't need extest any longer - Plasma added libei support and Xwayland can be built with libei support to replace the XTEST functions.

**Comment by Supreeeme** [comment]
Hm, this actually occurs regardless of whether extest is active for me.

**Comment by Zeglius** [comment]
After testing a bit more, it seems the culprit was switcheroo not working properly.
 https://github.com/ublue-os/bazzite/pull/1676#issuecomment-2365155244

Seems there was some commonality whenever I and others were testing just for the fact that switcheroo didn't trigger because it was being done in the terminal, where switcheroo only triggered when steam was launched from the app menu. 

I'm sorry for any headache this issue might have caused.
