### ISSUE TITLE
wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by nab-os** [Supreeeme/extest#2]
Hi,  

OS: Fedora Linux 37 (Workstation Edition)  

It builds correctly with a 32bit toolchain but when I start steam with this command:  
```
LD_PRELOAD=target/i686-unknown-linux-gnu/release/libextest.so steam
```

I receive a lot of the following error:  
```
ERROR: ld.so: object '/home/nabos/clones/extest/target/i686-unknown-linux-gnu/release/libextest.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

What can I do to try to debug this issue ?  

To test if it works I configured a desktop configuration for my steam controller, opened `wev` and tried to press some buttons on the controller. Am I right to think that with extest working `wev` should receive and display the inputs ?  

Thank you for your work

**Comment by Supreeeme** [comment]
The ELFCLASS32 "error" is expected - Steam launches 32 bit and 64 bit processes, so when the 64 bit processes attempt to preload a 32 bit library you get that. It's annoying that it's spammed so much but it can be ignored.
I would expect to see wev output though - does the mouse not work for you?

**Comment by nab-os** [comment]
> The ELFCLASS32 "error" is expected - Steam launches 32 bit and 64 bit processes, so when the 64 bit processes attempt to preload a 32 bit library you get that. It's annoying that it's spammed so much but it can be ignored.  

Ho ok I understand, thanks.

> I would expect to see wev output though - does the mouse not work for you?

No, nothing from the steam controller is logged on `wev`, but I can still interact with steam via the controller.
Can you recommend me a way to check if the virtual device is created correctly ?

**Comment by Supreeeme** [comment]
If you use `libinput list-devices`, you should see a device named `extest fake device`. The device is only created after you do something with the controller so be sure you press a button or swipe the trackpad on the controller or something.

**Comment by nab-os** [comment]
It doesn't seem to work.  
The only thing related to the controller is the `Valve Software Steam Controller` entry, no `extest fake device` listed.  
What can I do to help you understand what is missing or not working ?

**Comment by Supreeeme** [comment]
Is your user in the `input` group?

**Comment by nab-os** [comment]
I already was and I checked and rechecked again, it is x)

**Comment by Supreeeme** [comment]
Hmm, here's something you can try to check if uinput is even working properly:
1. Clone this repo: https://github.com/emberian/evdev
2. Run `cargo run --example virtual_mouse`

You should see the mouse move around (up-down, left-right). If that doesn't work something is likely wrong with your uinput permissions.

**Comment by nab-os** [comment]
Ok, this test is working correctly
Could it be my steam version or something related to steam not loading the library correctly ?

**Comment by Supreeeme** [comment]
I just noticed you're using the relative path to preload. Could you try using the absolute path with LD_PRELOAD? Kind of a shot in the dark though.

**Comment by nab-os** [comment]
I tried and nothing changed
If I put some debug message in the sources should I see them in my terminal ?

**Comment by nab-os** [comment]
Well, I'm not sure of what happened but I pulled the last merge and it now works. I guess it's solved now x)
Thank you for your time and your work :)
