### ISSUE TITLE
Issues with modifiers

### ISSUE THREAD

**Issue by KyleGospo** [Supreeeme/extest#5]
Hi, first I wanted to say thanks for making this, it's incredible that Steam Input can finally just be used on Wayland.

I ran into this issue in testing the Steam keyboard. The Tab key does nothing, and modifiers like caps lock and left shift don't change the output.

Tab is the odd one since it's not a modifier, in my testing it seems as if it doesn't even fire XTestFakeKeyEvent.

**Comment by Supreeeme** [comment]
Is this for the keyboard specifically, or generally with any config? I haven't tested the keyboard much, but testing it now with this reply, left shift and caps lock work without issue. I can confirm though tab however doesn't work, and I'll see if I can figure that one out.

**Comment by KyleGospo** [comment]
Keyboard specifically, shift and caps lock are resulting in the same letters/symbols as if they were off. I'll try and record a video.

**Comment by KyleGospo** [comment]
https://youtu.be/vDzn1ZcpGb4?si=m1oB0Vc9lblCke3N

**Comment by Supreeeme** [comment]
Ah, sorry, I completely forgot about this issue. Been a bit busy working on other projects, but I'll try and take a look sometime next  week.

**Comment by Supreeeme** [comment]
Ok, got around to this and fixed the tab key. However I'm not able to reproduce the issues with Shift. From your video, are you using the Steam Deck kernel on Fedora? Would you be able to test with a normal kernel?

**Comment by KyleGospo** [comment]
> Ok, got around to this and fixed the tab key. However I'm not able to reproduce the issues with Shift. From your video, are you using the Steam Deck kernel on Fedora? Would you be able to test with a normal kernel?

Stock Fedora kernel with minor kmods to add Steam Deck drivers for things like fan control. I'll give the new version a re-test and report back. Any logs you'd like?

**Comment by Supreeeme** [comment]
Just anything interesting from the steam output, of there is anything

**Comment by KyleGospo** [comment]
I can confirm that tab works and I can no longer reproduce the bug with shift.

Thank you so much!

**Comment by KyleGospo** [comment]
@Supreeeme Found one remaining issue, left and right parentheses aren't functioning for me.

In my testing I've done the following:
1: Loaded up xev in X11 and confirmed the correct key codes are shown for ( and ) from the steam keyboard
2: Loaded up wev in GNOME Wayland and confirmed nothing is registered for those same two keys.

**Comment by Supreeeme** [comment]
Sorry, holidays are a busy time...
Anyway, got around to fixing this too. Hopefully there are no more of these keys missing...

**Comment by KyleGospo** [comment]
Works perfectly, can't thank you enough!

**Comment by RodoMa92** [comment]
Sadly I still have some keys that seem to make the current field defocus (might be bound now to the tab key), which are: @, #, { and }. If you can make them behave, thanks a lot :)
